package com.mogujie.dao.entity;

import com.mogujie.orm.mybatis.plugin.api.annotation.Column;
import com.mogujie.orm.mybatis.plugin.api.annotation.Id;
import com.mogujie.orm.mybatis.plugin.api.annotation.Table;

import java.util.Date;

/**
 * Created by laibao
 */
@Table(name = "user")
public class User {

    private Long idx ;

    private String no ;

    private String name ;

    private String password ;

    private String nickname ;

    private String mobile ;

    private String educational ;

    private Long companyId ;

    private Long org_id ;

    private Long post_id ;

    private Long hierarchy_id ;

    private Integer position ;

    private Date entrant_date ;

    private Date resign_date ;

    private Integer status ;

    private Integer type ;

    private Long v_manager ;

    private Long tutor ;

    private String avatar ;

    private Integer flow_state ;

    @Id(autoGeneratedValue = true)
    @Column(dbCloumn = "id")
    public Long getIdx() {
        return idx;
    }

    public void setIdx(Long idx) {
        this.idx = idx;
    }

    public String getNo() {
        return no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEducational() {
        return educational;
    }

    public void setEducational(String educational) {
        this.educational = educational;
    }

    @Column(dbCloumn = "company_id")
    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getOrg_id() {
        return org_id;
    }

    public void setOrg_id(Long org_id) {
        this.org_id = org_id;
    }

    public Long getPost_id() {
        return post_id;
    }

    public void setPost_id(Long post_id) {
        this.post_id = post_id;
    }

    public Long getHierarchy_id() {
        return hierarchy_id;
    }

    public void setHierarchy_id(Long hierarchy_id) {
        this.hierarchy_id = hierarchy_id;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Date getEntrant_date() {
        return entrant_date;
    }

    public void setEntrant_date(Date entrant_date) {
        this.entrant_date = entrant_date;
    }

    public Date getResign_date() {
        return resign_date;
    }

    public void setResign_date(Date resign_date) {
        this.resign_date = resign_date;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getV_manager() {
        return v_manager;
    }

    public void setV_manager(Long v_manager) {
        this.v_manager = v_manager;
    }

    public Long getTutor() {
        return tutor;
    }

    public void setTutor(Long tutor) {
        this.tutor = tutor;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getFlow_state() {
        return flow_state;
    }

    public void setFlow_state(Integer flow_state) {
        this.flow_state = flow_state;
    }

    @Override
    public String toString() {
        return "User{" +
                "idx=" + idx +
                ", no='" + no + '\'' +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                ", nickname='" + nickname + '\'' +
                ", mobile='" + mobile + '\'' +
                ", educational='" + educational + '\'' +
                ", companyId=" + companyId +
                ", org_id=" + org_id +
                ", post_id=" + post_id +
                ", hierarchy_id=" + hierarchy_id +
                ", position=" + position +
                ", entrant_date=" + entrant_date +
                ", resign_date=" + resign_date +
                ", status=" + status +
                ", type=" + type +
                ", v_manager=" + v_manager +
                ", tutor=" + tutor +
                ", avatar='" + avatar + '\'' +
                ", flow_state=" + flow_state +
                '}';
    }
}
